<!DOCTYPE html>
<!--[if lt IE 7]>	<html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>	<html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>	<html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<!-- sasaki change title 2014/05/09 -->
<!-- title>Kosei Pharma Ltd</title -->
<title>Kosei Pharma Ltd - Pharmaceutical Wholesaler</title>

<meta name="description" content="&quot;Kosei Pharma&quot; UK pharmaceutical wholesaler, we supply European parallel import stocks and Generics to pharmacies, hospitals and doctors." />
<meta name="keywords" content="pharmaceutical, medicine, wholesaler, pharmacy, hospital, doctor, UK, England, European, parallel import, pi,  generic, license, repackaging, labelling, quality,  over the counter and pharmacy medicines, online pharmacy, sales, distribution, import, process" />
<meta name="robots" content="INDEX,FOLLOW" />
<link rel="icon" href="http://koseipharma.com/skin/frontend/default/kosei/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="http://koseipharma.com/skin/frontend/default/kosei/favicon.ico" type="image/x-icon" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="HandheldFriendly" content="True" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="address=no" />

<script type="text/javascript" src="http://fast.fonts.net/jsapi/2889193f-9970-4d26-abd4-64a436ff423f.js"></script>

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8">
<!-- sasaki add google analytics tracking code 2014/04/30 -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49003700-1', 'koseipharma.com');
  ga('send', 'pageview');

</script>

<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="cleartype" content="on" />
<![endif]-->

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = 'http://koseipharma.com/js/blank.html';
    var BLANK_IMG = 'http://koseipharma.com/js/spacer.gif';
//]]>
</script>
<![endif]-->

<link type="text/css" rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/cupertino/jquery-ui.min.css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>

<script>!window.jQuery && document.write(unescape('%3Cscript src="http://koseipharma.com/skin/frontend/default/kosei/js/jquery.min.js"%3E%3C/script%3E'))</script>


<link rel="stylesheet" type="text/css" href="http://koseipharma.com/skin/frontend/default/kosei/css/styles.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://koseipharma.com/skin/frontend/default/kosei/css/layout.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://koseipharma.com/skin/frontend/default/kosei/css/font-awesome.css" media="all" />
<script type="text/javascript" src="http://koseipharma.com/js/prototype/prototype.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/lib/ccard.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/prototype/validation.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/scriptaculous/builder.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/scriptaculous/effects.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/scriptaculous/dragdrop.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/scriptaculous/controls.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/scriptaculous/slider.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/varien/js.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/varien/form.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/varien/menu.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/mage/translate.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/mage/cookies.js"></script>
<script type="text/javascript" src="http://koseipharma.com/js/varien/weee.js"></script>
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src="http://koseipharma.com/skin/frontend/default/kosei/js/respond.min.js"%3E%3C/script%3E'))</script>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src="http://koseipharma.com/skin/frontend/default/kosei/js/html5.js"%3E%3C/script%3E'))</script>
<![endif]-->

<script type="text/javascript">
//<![CDATA[
Mage.Cookies.path     = '/';
Mage.Cookies.domain   = '.koseipharma.com';
//]]>
</script>

<script type="text/javascript">
//<![CDATA[
optionalZipCountries = ["HK","IE","MO","PA"];
//]]>
</script>
<script type="text/javascript">//<![CDATA[
        var Translator = new Translate([]);
        //]]></script><link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.pack.js"></script></head>
<body class=" cms-index-index cms-home">
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a></p>
<![endif]-->
<!-- BEGIN GOOGLE ANALYTICS CODEs -->
<script type="text/javascript">
//<![CDATA[
    var _gaq = _gaq || [];
    
_gaq.push(['_setAccount', 'UA-49007836-1']);
_gaq.push(['_trackPageview']);
    
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

//]]>
</script>
<!-- END GOOGLE ANALYTICS CODE -->
<div class="wrapper">
        <noscript>
        <div class="global-site-notice noscript">
            <div class="notice-inner">
                <p>
                    <strong>JavaScript seems to be disabled in your browser.</strong><br />
                    You must have JavaScript enabled in your browser to utilize the functionality of this website.                </p>
            </div>
        </div>
    </noscript>
    <div class="page">
        
<!-- sasaki add 2014/05/14 top search -->

<script type="text/javascript" src="http://koseipharma.com/skin/frontend/default/kosei/js/product_search.js"></script>	

<div class="header-container">
    
        <div class="quick-access">
            <div class="gridContainer">
                <!-- sasaki add My Account 2014/04/14 --> 
                <p class="welcome-msg">Welcome, Kosei Pharma!                 
                <a href="http://koseipharma.com/customer/account/">My Account</a></p>
                <ul class="links">      
                    <li class="first"><a href="http://koseipharma.com/customer/account/logout/">Log Out</a></li>    
                        <li class=" last"><a href="http://koseipharma.com/customer/account/create/" title="My Account">Register</a></li>
                </ul>
        </div>
        </div>
<header class="header gridContainer">        
                <h1><a href="http://koseipharma.com/" title="Kosei Pharma" class="logo"><img src="http://koseipharma.com/skin/frontend/default/kosei/images/logo.png" alt="Kosei Pharma"></a></h1>
                
                <div class="my-basket" style="display: none;"><div class="block-cart-header">
    <!--<img id="basket_icon" src="http://koseipharma.com/skin/frontend/base/default/images/basket.png"  alt="" />-->
    <span id="basket_title">View basket</span>    <div class="block-content cat_header">
                        <p class="empty">0 item(s)</p>
        </div>
            <button type="button" title="Checkout" class="button btn-disabled checkout-btn" onclick="setLocation('http://koseipharma.com/checkout/onepage/')" disabled=""><span><span>Checkout</span></span></button>   
     </div>
<script>
	jQuery('.block-cart-header .cart-content').hide();
	jQuery('.header .my-basket .block-cart-header').hover(
			function(){jQuery('.block-cart-header .cart-content').stop(true, true).slideDown(400);},
			function(){	jQuery('.block-cart-header .cart-content').stop(true, true).delay(400).slideUp(300);}
		);
</script></div>
        
<!-- sasaki delete serach_mini_form -->

<form id="search_mini_form" action="http://koseipharma.com/catalogsearch/result/" method="get">
    <div class="form-search">
        <label for="search">Search:</label>
        <input id="search" type="text" name="q" value="" class="input-text" maxlength="128" autocomplete="off">
        <button type="submit" title="Search" class="button"><span><span>Search</span></span></button>
        <div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', 'Search entire store here...');
            searchForm.initAutocomplete('http://koseipharma.com/catalogsearch/ajax/suggest/', 'search_autocomplete');
        //]]>
        </script>
    </div>
</form>
        
        <!-- sasaki add 2014/05/14 --> 
        <div style="clear:both; float:left; margin-top:10px; font-family: Arial, Helvetica, sans-serif; margin-bottom:0px;">  
          <div><span style="font-size:19px; color:#2E3192;">TELEPHONE ORDER: </span><span style="font-size:19px; color:#14b604;">0800 193 5051(Free Phone)</span></div>
          <div><span role="status" aria-live="polite" class="ui-helper-hidden-accessible"></span><input id="txtKeywd" type="search" value="Search products" class="ui-autocomplete-input" autocomplete="off"></div> 
        </div>

        <div style="float: left; position:relative; top :35px; left:30px;"> 
          <div style="float: left;"><a href="http://koseipharma.com/product.html" class="level-top"><button id="online_order_btn">ONLINE ORDER</button></a></div>
          <div style="float: left;"><a href="http://koseipharma.com/line-up.php"><button id="online_quotation_btn">ONLINE QUOTATION</button></a></div> 
        </div>

    </header>
</div>


<a class="toggleMenu" href="#"><i class="fa fa-bars"></i><span>Menu</span></a>
<nav class="nav-container">
    <ul id="nav" class="gridContainer">
        <li class="home active"><a href="http://koseipharma.com/">Home</a></li>    
        		<li  class="level0 nav-1 first last level-top"><a href="http://koseipharma.com/product.html"  class="level-top" ><span>Products</span></a></li>                
        <li class=''><a href="http://koseipharma.com/about-us"><span>About us</span></a></li>
                <li class=''><a href="http://koseipharma.com/career"><span>Careers</span></a></li>
        <li class=''><a href="http://koseipharma.com/contacts"><span>Contact us</span></a></li>
    </ul>
</nav>


<div class="main-container col1-layout">
	<div class="main gridContainer">
		<div class="col-main" data-twttr-rendered="true" itemscope itemtype="http://schema.org/WebPage">
			<div class="home-top"><div class="home-content">


<div style="font-size:40px; color:#2E3192; margin-top:15px; margin-bottom:15px; margin-left:60px;">Sorry, this page is under construction</div>

<?php
   //session_name("frontend");
   //session_start();
setcookie($_COOKIE["frontend"]);
   echo '<br><br>[from registration session]' . session_name() . ':' . session_id() . '<br>'; 
   echo "COMPANY: " . $_SESSION["company"]  . "<br>"; 
   echo "NAME: " . $_SESSION["name"] . "<br>";
   echo "TELEPHONE: " . $_SESSION["telephone"] . "<br>";
   echo "EMAIL: " . $_SESSION["email"] . "<br>";
   echo "ADDRESS: " . $_SESSION["address"] . "<br>";
   echo "WDL or Pharmacy No: " . $_SESSION["wdl-or-pha"] . "<br>";
   echo "Company Reg No: " . $_SESSION["companyNo"] . "<br>";
?>


<div style="font-size:30px; color:#2E3192; margin-top:15px; margin-bottom:15px; margin-left:60px;">Lineup</div>
<div style="font-size:17px; color:#333; margin-top:10px; margin-bottom:20px; margin-left:60px;">As the growing company, we are actively expanding our products. If you did not find what you were looking for today, please visit us again or <a href="http://koseipharma.com/index.php/webforms/index/index/id/4/" target=h_blankh>contact our sales team</a> with your request.</div>

<div class="line-up-list">
<?php
$all = array(
"ABILIFY",
"ACCU-CHECK",
"ACCURETIC",
"ACTONEL",
"ACTOS",
"ADALAT",
"ALATERIS",
"ALLEGRON",
"ALPHAGAN",
"ALVESCO",
"ANAFRANIL",
"APROVEL",
"AQUACEL",
"ARCOXIA",
"ARICEPT",
"ARIMIDEX",
"AROMACIN",
"ATROVENT",
"AUGMENTIN",
"AVAMYS",
"AVODART",
"AZARGA",
"AZITHROMYCIN",
"BACTROBAN",
"BD",
"BETNOVATE",
"BETOPTIC",
"BEZALIP",
"BONEFOS",
"BONVIVA",
"BUSCOPAN",
"CACIT",
"CALCICHEW",
"CANESTEN",
"CARDICOR",
"CASODEX",
"CAVILON",
"CELEBREX",
"CELLCEPT",
"CELLUVISC",
"CILOXAN",
"CIPRALEX",
"CIPRAMIL",
"CIPROFIBRATE",
"CIRCADIN",
"CLOPIXOL",
"CO-APROVEL",
"CO-IRBESARTAN",
"COMBIGAN",
"COMBODART",
"COMPETACT",
"CONTOUR",
"COVERSYL",
"COZAAR",
"CREON",
"CRESTOR",
"CYMBALTA",
"DALACIN",
"DANTRIUM",
"DEPO-MEDRONE",
"DERMOVATE",
"DETRUSITOL",
"DIAMICRON",
"DIANETTE",
"DICLOFENAC",
"DICLOMAX",
"DIFLUCAN",
"DIOVAN",
"DIPROSALIC",
"DITROPAN",
"DOMPERIDONE",
"DOVOBET",
"DULOXETINE",
"DUOTRAV",
"DURAPHAT",
"EBIXA",
"EDRONAX",
"EFEXOR",
"EFIENT",
"EFUDIX",
"ENSURE",
"EPANUTIN",
"EPILIM",
"ESTRADERM",
"EUMOVATE",
"EXELON",
"FELDENE",
"FEMOSTON",
"FEMSEVEN",
"FLIXONASE",
"FLIXOTIDE",
"FLOMAXTRA",
"FLUCLOXACILLIN",
"FORADIL",
"FORTIJUICE",
"FORTISIP",
"FOSAMAX",
"FREESTYLE-OPTIUM",
"GLANDOSANE",
"GLUCOPHAGE",
"GLUCOMEN",
"HALF-INDERAL",
"HALF-SINEMET",
"HYPOVASE",
"IMDUR",
"IMIGRAN",
"INSPRA",
"ISTIN",
"JANUVIA",
"KENALOG",
"KEPPRA",
"LAMISIL",
"LARIAM",
"LESCOL",
"LEVITRA",
"LEVONELLE",
"LIPANTIL",
"LIPITOR",
"LOCERYL",
"LONITEN",
"LOSARTAN",
"LOTRIDERM",
"LUMIGAN",
"LUSTRAL",
"LYRICA",
"MADOPAR",
"MARVELON",
"MAXALT",
"MERCAPTOPURINE",
"MESTINON",
"METHOTREXATE",
"METHYLDOPA",
"MEZAVANT",
"MICARDIS",
"MIRAPEXIN",
"MOTILIUM",
"MULTAQ",
"NARAMIG",
"NASACORT",
"NEORAL",
"NEUPRO",
"NEURONTIN",
"NEXIUM",
"NORTRIPTYLINE",
"NOVOFINE",
"NUTRAMIGEN",
"OESTROGEL",
"OLMETEC",
"OMACOR",
"ONE-ALPHA",
"OPTIVE",
"OTOSPORIN",
"ONE-TOUCH",
"OVESTIN",
"OXIS-TURBOHALER",
"PARIET",
"PENFINE",
"PERCUTOL",
"PERSANTIN",
"PHENYTOIN",
"PLAVIX",
"PLETAL",
"PRIMIDONE",
"PROCORALAN",
"PROGRAF",
"PROPECIA",
"PROSCAR",
"PULMICORT",
"PURI-NETHOL",
"QVAR",
"RAPITIL",
"RASILEZ",
"REGURIN",
"REQUIP",
"ROZEX",
"SERC",
"SERETIDE",
"SEREVENT",
"SEROQUEL",
"SINEMET",
"SINGULAIR",
"SPIRIVA",
"SULFASALAZINE",
"SUPRALIP",
"TAVANIC",
"TEGRETOL",
"TELFAST",
"TELMISARTAN",
"TEOPTIC",
"TILDIEM",
"TIMOPTOL",
"TOPAMAX",
"TRANSIDERM",
"TRILEPTAL",
"TROSYL",
"TRUSOPT",
"URSOFALK",
"VALSARTAN",
"VENTOLIN",
"VESICARE",
"VIMPAT",
"VISCOTEARS",
"VOLTAROL",
"XATRAL",
"XENICAL",
"YASMIN",
"ZADITEN",
"ZAMADOL",
"ZANIDIP",
"ZINERYT",
"ZITHROMAX",
"ZONEGRAN",
"ZOVIRAX",
"ZYBAN",
"ZYDOL"
);

foreach ($all as &$product) {
echo '<div class="line-up-item"><a href="http://koseipharma.com/product.php?product=' . $product . '"><img src="http://koseipharma.com/skin/frontend/default/kosei/images/drug-icon.png"> ' . $product . "</a></div>\n";
} 
 
?>




</div>

     
			</div></div>
        </div>
    </div>
    <footer class="footer-container">
    <div class="footer gridContainer">
        <ul>
<li><a href="http://koseipharma.com/about-us">About Us</a></li>
<li><a href="http://koseipharma.com/terms-condition">Terms and Conditio</a><a href="http://koseipharma.com/terms-condition">n</a></li>
<li class="last privacy"><a href="http://koseipharma.com/privacy-policy-cookie-restriction-mode">Privacy Policy</a></li>
</ul><script type="text/javascript" src="http://koseipharma.com/skin/frontend/default/kosei/js/plugins.js"></script>
<script type="text/javascript" src="http://koseipharma.com/skin/frontend/default/kosei/js/jquery.carouFredSel-6.2.1.js"></script>
<script type="text/javascript" src="http://koseipharma.com/skin/frontend/default/kosei/js/scripts.js"></script>
        <ul class="footer-phones">
            <li>Company No. 7236727</li>
            <li>VAT No. GB111184167</li>
            <li>WHOLESALE-DEALERS LICENCE-WL39352</li>
            <li>MANUFACTURE'S/IMPORTER'S LICENCE-MIA39352</li>
            <li>MANUFACTURE'S "SPECIALS" LICENCE-MS39352</li>
        </ul>
        <div class="footer-text">
            <span>&copy; 2013Copyright Information</span>
            <!-- sasaki delete 2014/03/14
            <address>Designed By Best Response Media</address>
            -->
        </div>
    </div>
</footer>
            </div>
</div>
</body>
</html>